import type { TranscriptContext } from "./transcriptTypes";

export function downloadJSON(filename: string, data: unknown) {
  const blob = new Blob([JSON.stringify(data, null, 2)], {
    type: "application/json",
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadMarkdown(filename: string, content: string) {
  const blob = new Blob([content], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportTranscriptJSON(context: TranscriptContext) {
  downloadJSON("recall-transcript-context.json", context);
}

export function exportTranscriptMarkdown(context: TranscriptContext) {
  const md = buildTranscriptMarkdown(context);
  downloadMarkdown("recall-transcript-summary.md", md);
}

function buildTranscriptMarkdown(context: TranscriptContext): string {
  const s = context.summary;
  const lines: string[] = [
    "# Recall Transcript Summary",
    "",
    "## Summary",
    `- Commands: ${s.command_count}`,
    `- Files changed: ${s.file_change_count}`,
    `- Errors: ${s.error_count}`,
    `- Warnings: ${s.warning_count}`,
    `- Verification checks: ${s.verification_count}`,
    `- Commits: ${s.commit_count}`,
    "",
  ];

  if (context.commands.length > 0) {
    lines.push("## Commands");
    lines.push("| Status | Shell | Command |");
    lines.push("|---|---|---|");
    for (const cmd of context.commands) {
      const statusEmoji = cmd.status === "pass" ? "✅" : cmd.status === "fail" ? "❌" : "⏳";
      lines.push(`| ${statusEmoji} ${cmd.status} | ${cmd.shell} | \`${cmd.command.replace(/`/g, "'")}\` |`);
    }
    lines.push("");
  }

  if (context.files_changed.length > 0) {
    lines.push("## Files Changed");
    lines.push("| Action | Path |");
    lines.push("|---|---|");
    for (const f of context.files_changed) {
      lines.push(`| ${f.action} | \`${f.path}\` |`);
    }
    lines.push("");
  }

  if (context.errors.length > 0) {
    lines.push("## Errors");
    for (const e of context.errors) {
      lines.push(`- **${e.code}**: ${e.message}`);
    }
    lines.push("");
  }

  if (context.warnings.length > 0) {
    lines.push("## Warnings");
    for (const w of context.warnings) {
      lines.push(`- ${w.message}`);
    }
    lines.push("");
  }

  if (context.verification.length > 0) {
    lines.push("## Verification");
    for (const v of context.verification) {
      const emoji = v.status === "pass" ? "✅" : v.status === "fail" ? "❌" : "⏳";
      lines.push(`- ${emoji} ${v.name}`);
    }
    lines.push("");
  }

  if (context.commits.length > 0) {
    lines.push("## Commits");
    for (const c of context.commits) {
      lines.push(`- \`${c.hash}\` — ${c.message || "(no message)"}`);
    }
    lines.push("");
  }

  if (context.next_steps.length > 0) {
    lines.push("## Next Steps");
    for (const ns of context.next_steps) {
      lines.push(`- ${ns}`);
    }
    lines.push("");
  }

  lines.push("## Notes");
  lines.push("This was generated by recall-transcript-parser-v0 from pasted text.");
  lines.push("");

  return lines.join("\n");
}
